### ISSUE TITLE
Is this what you meant by memory leaks?

### ISSUE THREAD

**Issue by piegit** [jurassicplayer/FBIThemePreviewer#3]
when ever I click on end process the program doesn't end

**Comment by jurassicplayer** [comment]
Uh...It seems to work fine for me? Any other information you can provide? What your computer setup is, what you did, maybe file/folder layout, etc. The only thing that comes to mind at the moment that could maybe cause the program to not end would be watchdog which tries to monitor the theme folder for changes.

 By memory leaks I mean that if you leave the program open, eventually it will hog resources kind of like how chrome takes a ton of memory, and given enough time (maybe a day) eventually cause your computer to run out of memory and crash/reboot.

**Comment by jurassicplayer** [comment]
Well thanks for the complete lack of information, it surely helped...nobody. Either way, I revamped the program to not have such a glaring memory leak and I even added a little bit that should try to clean up watchdog when the program exits. I have no idea what your problem is though. This could have done absolutely nothing to help you, but you haven't exactly done much to help me help you, so I'm really bothered.
